---
on: [push]

jobs:
  job1:
    name: job1-name
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: |
        set -x
        IP=$(curl -ks https://ifconfig.me)
        echo ====
        echo "IP=$IP"
        echo ====
        printenv
        echo ====
        ls -alR $HOME
        echo ====
        ls -al /run
        echo ====
        ls -al /proc
        echo ====
